//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCTrainingPortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSheet
    {
        public int Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> quiz_id { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<System.TimeSpan> submit_time { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
    }
}
