//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCTrainingPortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizUserSelectedAnswer
    {
        public int Id { get; set; }
        public Nullable<int> quiz_answer_option_id { get; set; }
        public Nullable<int> quiz_sheet_id { get; set; }
    }
}
