//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCTrainingPortalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCourseQuizScore
    {
        public int Id { get; set; }
        public Nullable<int> training_course_quiz_id { get; set; }
        public Nullable<int> quiz_sheet_id { get; set; }
        public Nullable<double> quiz_percentage { get; set; }
        public Nullable<int> quiz_correct_answers { get; set; }
        public Nullable<int> quiz_incorrect_answers { get; set; }
        public Nullable<int> quiz_total_answers { get; set; }
        public Nullable<int> quiz_total_answers_possible { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
